services:
    miniflux_ai:
        container_name: miniflux_ai
        build:
          context: .
        restart: always
        environment:
            TZ: America/Chicago
        volumes:
            - ./config.yml:/app/config.yml
